language: scala
jdk: oraclejdk8
sudo: false
script:
  - sbt +test 
cache:
  directories:
    - $HOME/.ivy2/cache
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com.lightbend.play/play-socket-io*
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm

before_script:
  - "mkdir -p ~/tmp/bin"
  - "pushd ~/tmp/bin && wget -c https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz && tar -xzvf geckodriver-v0.24.0-linux64.tar.gz && popd"
  - "chmod -vv +x ~/tmp/bin/*"
  - "export PATH=$HOME/tmp/bin:$PATH"
addons:
  firefox: "latest"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
